name: pusher
descript: a sample dart web project
version: 1.0.0
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.4.36
  jaguar_orm: ^2.2.6
  jaguar_query_postgres: ^2.2.6

dev_dependencies:
  build_runner:
  json_serializable: ^3.0.0
  jaguar_orm_gen: